### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Yttehs-HDX/zsh-zpacman#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Yttehs-HDX** [comment]
Done.

**Comment by Yttehs-HDX** [comment]
The plugin `zsh-zpacman` is specific for my own omz plugin manager [`ZPacman`](https://github.com/Yttehs-HDX/zpacman).

Please considering add appropriate description.
